name: amazon_sales_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.1.4
  - numpy=1.26.2
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - jupyter=1.0.0
  - jupyterlab=4.0.9
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - plotly=5.18.0
  - pip
  - pip:
    - ipywidgets>=8.1.1
